MODE=ROUTER
#MODE=SMART-BRIDGE
#MODE=RPL-RELAY
#MODE=FULL-TRANSPARENT-BRIDGE
#MODE=NDP-ROUTER
#MODE=6LR
#MODE=RPL-ROOT

RAW_ETH=0
BRIDGE=1
#CREATE_BRIDGE=6LBR
DEV_BRIDGE=br0
DEV_TAP=tap0
DEV_ETH=eth0
#RAW_ETH_FCS=1
RAW_ETH_FCS=0
#ETH_JOIN_BRIDGE=0
RA_DAEMON=1
DEFAULT_ROUTE=1
RA_INTERVAL=30
RA_LIFETIME=1800

#Check USB enumeration ACMx or USBx (by running lsusb in console)
#DEV_RADIO=/dev/ttyACM0
DEV_RADIO=/dev/ttyUSB1
BAUDRATE=115200

LOG_LEVEL=5
LOG_6LBR_OUT=/var/log/6lbr.log
