#MODE=ROUTER
#MODE=SMART-BRIDGE
#MODE=RPL-RELAY
#MODE=FULL-TRANSPARENT-BRIDGE
#MODE=NDP-ROUTER
MODE=6LR
#MODE=RPL-ROOT

RAW_ETH=0
BRIDGE=0
DEV_BRIDGE=br0
DEV_TAP=tap0
DEV_ETH=eth0
#RAW_ETH_FCS=1
RAW_ETH_FCS=0
#RADIO_TX_POWER=5 
#RADIO_CHANNEL=26
 
#Check USB enumeration ACMx or USBx (by running lsusb in console)
#DEV_RADIO=/dev/ttyACM0
DEV_RADIO=/dev/ttyUSB1
BAUDRATE=115200

LOG_LEVEL=4
LOG_SERVICES=-1
LOG_6LBR_OUT=/var/log/6lbr.log

